name: awc_complaints_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.9+6

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  dotted_border: ^2.0.0+3
  font_awesome_flutter: ^10.5.0
  #  http: ^0.12.2
  http: ^1.1.0
  shared_preferences: ^2.0.4
  #  firebase_messaging: ^7.0.3
  #  firebase_messaging: ^10.0.0
  #firebase_core: ^1.2.0
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  overlay_support: ^2.1.0

  intl: ^0.18.1

  path_provider: ^2.0.1
  path: ^1.8.0
  #  image_picker: ^0.6.5+2
  image_picker: ^1.0.4
  connectivity: ^3.0.3
  #  im_stepper: ^0.1.2+10
  status_change: ^2.0.0
  #  multi_page_form:
  #  nb_utils: 3.3.5-nullsafety

  cached_network_image: any
  pull_to_refresh: ^2.0.0
  photo_view: ^0.14.0
  badges: ^3.1.2
  nb_utils: ^6.0.4

  html: ^0.15.0
  flutter_local_notifications: ^15.1.1
  flutter_app_badger: ^1.2.0
  flutter_phoenix: ^1.0.0
  get: ^4.3.8


  #  provider:

  flutter_localizations:
    sdk: flutter




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/pizza.jpg
    - assets/logo.png
    - assets/background_img.png
    - assets/app_background.png
    - assets/login_backgroun.png
    - assets/notification.png
    - assets/nav_home.png
    - assets/nav_complaint.png
    - assets/upload_icon.png
    - assets/pending_icon.png
    - assets/done_icon.png
    - assets/frame_img.png
    - assets/step_1_primary.png
    - assets/step_2_primary.png
    - assets/step_3_primary.png
    - assets/step_2_grey.png
    - assets/step_3_grey.png
    - assets/bottom_home.png
    - assets/bottom_complaint.png
    - assets/complaint_succes.png
    - assets/notification_bell.png
    - assets/complaint_icon_dot.png
    - lang/en.json
    - lang/id.json


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
